name: Optimize Images

on:
  push:
    paths:
      - lib/**/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    if: "!startsWith(github.ref, 'refs/tags') && !startsWith(github.event.head_commit.message, 'chore[github-actions]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Optimize images
        uses: gabrielecanepa/optimize-images@v1
        id: optimize_images
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          export-webp: true
          debug: true
      - name: Create pull request
        if: steps.optimize_images.outputs.markdown_report != ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: "[GitHub Actions] Optimize Images"
          body: ${{ steps.optimize_images.outputs.markdown_report }}
          commit-message: "chore[github-actions]: optimize images"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          labels: optimization
          delete-branch: true
