name: Optimize Images
on:
  push:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: calibreapp/image-actions@main
        id: optimize_images
        with:
          compressOnly: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v4
        if: steps.optimize_images.outputs.markdown != ''
        with:
          title: Optimize images
          branch-suffix: timestamp
          commit-message: "chore[bot]: optimize images"
          body: ${{ steps.optimize_images.outputs.markdown }}
