name: Release

on:
  push:
    tags:
      - v*
      - v*.*
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      body: ${{ steps.build.outputs.body }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        id: get_latest_release
        with:
          repository: ${{ github.repository }}
      - name: Build new release
        id: build
        env:
          HOST: ${{ vars.HOST }}
          LIB: ${{ vars.LIB }}
          REPO: ${{ github.repository }}
          LATEST_TAG: ${{ steps.get_latest_release.outputs.release }}
          NEW_TAG: ${{ github.ref_name }}
        run: |
          . ${{ github.workspace }}/bin/build-release.sh >> RELEASE.md
      - name: Publish new release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: RELEASE.md
          artifacts: lib/*
          generateReleaseNotes: true
          makeLatest: true
